// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace CodeMania.IOS
{
	public partial class AmountEditViewController : UIViewController
	{
		public AmountEditViewController (IntPtr handle) : base (handle)
		{
		}

		partial void DonePressed (MonoTouch.Foundation.NSObject sender)
		{

		}
	}
}
