// This file has been autogenerated from a class added in the UI designer.

using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using SQLite.Net.Interop;

namespace CodeMania.IOS
{
	public partial class AmountEditViewController : UIViewController
	{
		public AmountEditViewController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			AmountTextField.BecomeFirstResponder();
		}

		public float Amount
		{
			get
			{
				var val = AmountTextField.Text;
				float res;
				if (float.TryParse(val, out res))
				{
					return res;
				}
				return 0;
			}

		}
	}
}
