// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using CodeMania.Core.Model;

namespace CodeMania.IOS
{
	public partial class QuickCurrencyCell : UICollectionViewCell
	{
		public static NSString Key = new NSString ("QuickCurrencyCell");

		public QuickCurrencyCell (IntPtr handle) : base (handle)
		{
		}

		public void Setup(CurrencyRate rate, float baseAmount)
		{
			CurrencyNameLabel.Text = rate.Id;
			ExchangeRateValueLabel.Text = string.Format ("{0:0.0000}", rate.Rate);
			CurrencyValueLabel.Text = (rate.Rate * baseAmount).FormatCurrency (rate.Id);

		}
	}
}
