// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace CodeMania.IOS
{
	public partial class QuickCurrencyHeaderCell : UICollectionReusableView
	{
		public static NSString Key = new NSString ("QuickCurrencyHeaderCell");
		public QuickCurrencyHeaderCell (IntPtr handle) : base (handle)
		{
		}

		public void Setup(string currencyName, float currencyAmount)
		{
			CurrencyNameLabel.Text = currencyName;
			CurrencyValueLabel.Text = currencyAmount.FormatCurrency (currencyName);

			var image = UIImage.FromFile (string.Format ("images/{0}.jpg", currencyName));
			if (image != null)
			{
				CurrencyFlagImageView.Image = image;
			}
		}
	}
}
