#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("CodeMania.Android.Resource", IsApplication=true)]

namespace CodeMania.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::CodeMania.Android.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::CodeMania.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_refresh = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AUD = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BTC = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int CAD = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int CHF = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int DOG = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int EUR = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int GBP = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int INR = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int JPY = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int NZD = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int USD = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int action_refresh = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int backgroundLayout = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int currencyGridView = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int currencyName = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int currencyRate = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int currencyValue = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int flagImageView = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int newCurrencyAmount = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int relativeLayout1 = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CurrencyView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HeaderView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int NewCurrencyDialog = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int main_activity_actions = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int hello = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
